services: 
  server:
    build:
      context: .
      target: final
    ports:
      - 8080:8080
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    volumes:
      - ./GroupBot.Program/bot_data.db:/app/bot_data.db
      - ./logs:/app/logs
