version: '3.4'

services:
  groupbot:
    image: groupbot:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - bot_data:/app/data

volumes:
  bot_data:
